/**
 ****************************************************************************************************
 * @file        web_page.h - SD卡文件管理器 + WiFi设置面板
 ****************************************************************************************************
 */

#ifndef __WEB_PAGE_H_
#define __WEB_PAGE_H_

static const char INDEX_HTML[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"zh-CN\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0\">\n"
    "<title>SD\xE5\x8D\xA1\xE6\x96\x87\xE4\xBB\xB6\xE7\xAE\xA1\xE7\x90\x86\xE5\x99\xA8</title>\n"
    "<style>\n"
    "*{margin:0;padding:0;box-sizing:border-box}\n"
    "body{font-family:Arial,Helvetica,'PingFang SC','Microsoft YaHei',sans-serif;background:#f0f2f5;padding:12px;color:#333}\n"
    "h2{font-size:1.1rem;margin-bottom:4px;color:#1a1a2e}\n"
    ".bar{font-size:.8rem;color:#888;margin-bottom:10px;display:flex;align-items:center;flex-wrap:wrap;gap:6px}\n"
    ".bar a{color:#1a73e8;text-decoration:none}\n"
    ".bar a:hover{text-decoration:underline}\n"
    ".row{display:flex;align-items:center;padding:10px 12px;margin-bottom:1px;background:#fff;border-radius:4px;cursor:pointer;min-height:44px}\n"
    ".row:active{background:#e8f0fe}\n"
    ".row .icon{width:32px;text-align:center;margin-right:10px;font-size:1.2rem;flex-shrink:0}\n"
    ".row .name{flex:1;word-break:break-all;font-size:.9rem}\n"
    ".row .size{color:#999;font-size:.78rem;margin-left:8px;white-space:nowrap;flex-shrink:0}\n"
    ".err{background:#fff5f5;color:#c62828;padding:12px;border-radius:6px;font-size:.85rem;border:1px solid #ffcdd2}\n"
    ".tip{color:#888;font-size:.78rem;margin-top:4px}\n"
    ".info{font-size:.8rem;color:#888;margin-bottom:6px}\n"
    ".btn-refresh{background:none;border:1px solid #ccc;color:#666;padding:6px 12px;border-radius:4px;font-size:.8rem;cursor:pointer}\n"
    ".empty{text-align:center;padding:40px;color:#bbb}\n"
    /* 图片预览模态框 */
    ".modal{position:fixed;top:0;left:0;width:100%;height:100%;background:rgba(0,0,0,.85);z-index:100;display:flex;align-items:center;justify-content:center}\n"
    ".modal.hidden{display:none}\n"
    ".modal img{max-width:95%;max-height:90vh;object-fit:contain;border-radius:4px}\n"
    ".modal .close{position:fixed;top:12px;right:16px;color:#fff;font-size:1.8rem;cursor:pointer;z-index:101;line-height:1}\n"
    ".modal .dl-btn{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);background:#1a73e8;color:#fff;border:none;padding:10px 28px;border-radius:20px;font-size:.9rem;cursor:pointer;z-index:101;box-shadow:0 4px 12px rgba(0,0,0,.3)}\n"
    /* WiFi设置面板 */
    ".set-pnl{background:#fff;border-radius:8px;margin-bottom:10px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,.08)}\n"
    ".set-hdr{display:flex;align-items:center;padding:12px;cursor:pointer;min-height:44px;user-select:none}\n"
    ".set-hdr:active{background:#f5f5f5}\n"
    ".set-hdr .set-icon{font-size:1.2rem;margin-right:10px}\n"
    ".set-hdr .set-label{flex:1;font-size:.9rem;font-weight:600;color:#333}\n"
    ".set-hdr .set-ssid{font-size:.78rem;color:#1a73e8;margin-right:6px}\n"
    ".set-hdr .set-arrow{font-size:.8rem;color:#aaa;transition:transform .2s}\n"
    ".set-hdr .set-arrow.open{transform:rotate(90deg)}\n"
    ".set-body{display:none;padding:0 12px 12px 12px;border-top:1px solid #eee}\n"
    ".set-body.open{display:block}\n"
    ".set-body label{display:block;font-size:.78rem;color:#666;margin:10px 0 4px 0}\n"
    ".set-body input{width:100%;padding:10px;border:1px solid #ddd;border-radius:6px;font-size:.9rem;outline:none;-webkit-appearance:none}\n"
    ".set-body input:focus{border-color:#1a73e8;box-shadow:0 0 0 2px rgba(26,115,232,.15)}\n"
    ".set-body .btn-save{display:block;width:100%;margin-top:12px;padding:11px;background:#1a73e8;color:#fff;border:none;border-radius:6px;font-size:.9rem;font-weight:600;cursor:pointer;min-height:44px}\n"
    ".set-body .btn-save:active{background:#1557b0}\n"
    ".set-body .set-msg{font-size:.8rem;margin-top:8px;text-align:center;min-height:20px}\n"
    ".set-body .set-msg.ok{color:#2e7d32}\n"
    ".set-body .set-msg.err{color:#c62828}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<h2>\xF0\x9F\x93\x81 SD\xE5\x8D\xA1\xE6\x96\x87\xE4\xBB\xB6\xE7\xAE\xA1\xE7\x90\x86\xE5\x99\xA8</h2>\n"
    /* WiFi设置面板 */
    "<div class=\"set-pnl\">\n"
    "<div class=\"set-hdr\" onclick=\"tglSet()\">\n"
    "<span class=\"set-icon\">\xE2\x9A\x99</span>\n"
    "<span class=\"set-label\">WiFi \xE8\xAE\xBE\xE7\xBD\xAE</span>\n"
    "<span class=\"set-ssid\" id=\"hdrSsid\">BOSSCOM_USB_AP</span>\n"
    "<span class=\"set-arrow\" id=\"setArr\">\xE2\x96\xB6</span>\n"
    "</div>\n"
    "<div class=\"set-body\" id=\"setBody\">\n"
    "<label for=\"inpSsid\">WiFi \xE5\x90\x8D\xE7\xA7\xB0 (SSID)</label>\n"
    "<input type=\"text\" id=\"inpSsid\" maxlength=\"31\" placeholder=\"\xE8\xBE\x93\xE5\x85\xA5WiFi\xE5\x90\x8D\xE7\xA7\xB0\">\n"
    "<label for=\"inpPass\">WiFi \xE5\xAF\x86\xE7\xA0\x81</label>\n"
    "<input type=\"text\" id=\"inpPass\" maxlength=\"63\" placeholder=\"\xE8\x87\xB3\xE5\xB0\x91""8\xE4\xBD\x8D\xEF\xBC\x8C\xE7\x95\x99\xE7\xA9\xBA\xE8\xA1\xA8\xE7\xA4\xBA\xE5\xBC\x80\xE6\x94\xBE\xE7\xBD\x91\xE7\xBB\x9C\">\n"
    "<button class=\"btn-save\" onclick=\"svCfg()\">\xE4\xBF\x9D\xE5\xAD\x98\xE8\xAE\xBE\xE7\xBD\xAE</button>\n"
    "<div class=\"set-msg\" id=\"setMsg\"></div>\n"
    "</div>\n"
    "</div>\n"
    /* 文件列表区域 */
    "<div class=\"bar\" id=\"bread\"><a onclick=\"ld('/SD')\">/SD</a></div>\n"
    "<div class=\"info\" id=\"info\">\xE6\xAD\xA3\xE5\x9C\xA8\xE5\x8A\xA0\xE8\xBD\xBD...</div>\n"
    "<div id=\"content\"></div>\n"
    "<div style=\"margin-top:10px\"><button class=\"btn-refresh\" onclick=\"ld(cp)\">\xF0\x9F\x94\x84 \xE5\x88\xB7\xE6\x96\xB0</button></div>\n"
    /* 图片预览模态框 */
    "<div class=\"modal hidden\" id=\"modal\" onclick=\"clsM()\"><span class=\"close\">\xE2\x9C\x95</span><img id=\"modalImg\" src=\"\"><button class=\"dl-btn\" id=\"modalDlBtn\" onclick=\"event.stopPropagation();dl(cf)\">\xE2\xAC\x87 \xE4\xB8\x8B\xE8\xBD\xBD</button></div>\n"
    "<script>\n"
    "var cp='/SD';var cf='';\n"
    "var imgExts={png:1,jpg:1,jpeg:1,gif:1,bmp:1,svg:1,ico:1,webp:1};\n"
    /* WiFi设置 */
    "var setOpen=false;\n"
    "function tglSet(){\n"
    "setOpen=!setOpen;\n"
    "document.getElementById('setBody').className='set-body'+(setOpen?' open':'');\n"
    "document.getElementById('setArr').className='set-arrow'+(setOpen?' open':'');\n"
    "if(setOpen)ldCfg();\n"
    "}\n"
    "function ldCfg(){\n"
    "fetch('/api/wifi-config')\n"
    ".then(function(r){return r.json()})\n"
    ".then(function(d){\n"
    "if(d.ok){\n"
    "document.getElementById('inpSsid').value=d.ssid;\n"
    "document.getElementById('inpPass').value=d.password;\n"
    "document.getElementById('hdrSsid').textContent=d.ssid;\n"
    "}\n"
    "})\n"
    ".catch(function(){})\n"
    "}\n"
    "function svCfg(){\n"
    "var ssid=document.getElementById('inpSsid').value.trim();\n"
    "var pass=document.getElementById('inpPass').value;\n"
    "var msgEl=document.getElementById('setMsg');\n"
    "if(ssid.length<1||ssid.length>31){msgEl.className='set-msg err';msgEl.textContent='WiFi\xE5\x90\x8D\xE7\xA7\xB0\xE9\x9C\x80\xE8\xA6\x81""1-31\xE4\xBD\x8D';return}\n"
    "if(pass.length>0&&(pass.length<8||pass.length>63)){msgEl.className='set-msg err';msgEl.textContent='\xE5\xAF\x86\xE7\xA0\x81\xE9\x9C\x80\xE8\xA6\x81""8-63\xE4\xBD\x8D\xE6\x88\x96\xE7\x95\x99\xE7\xA9\xBA';return}\n"
    "msgEl.className='set-msg';msgEl.textContent='\xE6\xAD\xA3\xE5\x9C\xA8\xE4\xBF\x9D\xE5\xAD\x98...';\n"
    "fetch('/api/wifi-config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ssid:ssid,password:pass})})\n"
    ".then(function(r){return r.json()})\n"
    ".then(function(d){\n"
    "if(d.ok){msgEl.className='set-msg ok';msgEl.textContent=d.msg+' ('+ssid+')'}\n"
    "else{msgEl.className='set-msg err';msgEl.textContent=d.error}\n"
    "})\n"
    ".catch(function(e){msgEl.className='set-msg err';msgEl.textContent='\xE7\xBD\x91\xE7\xBB\x9C\xE9\x94\x99\xE8\xAF\xAF: '+e.message})\n"
    "}\n"
    "ldCfg();\n"
    /* 文件列表 */
    "function ld(p){\n"
    "cp=p;document.getElementById('info').textContent='\xE5\x8A\xA0\xE8\xBD\xBD '+p+' ...';document.getElementById('content').innerHTML='';\n"
    "fetch('/api/list?path='+encodeURIComponent(p))\n"
    ".then(function(r){return r.json()})\n"
    ".then(function(d){rnd(d)})\n"
    ".catch(function(e){document.getElementById('content').innerHTML='<div class=\"err\">\xE2\x9A\xA0 \xE7\xBD\x91\xE7\xBB\x9C\xE9\x94\x99\xE8\xAF\xAF: '+e.message+'</div>'})\n"
    "}\n"
    "function rnd(d){\n"
    "if(!d.ok){var h='<div class=\"err\">\xE2\x9A\xA0 '+d.error+'</div>';if(d.code==='SD_NOT_MOUNTED')h+='<div class=\"tip\">\xE8\xAF\xB7\xE5\x9C\xA8Windows\xE4\xB8\x8A\xE5\x8F\xB3\xE9\x94\xAE\xE5\xBC\xB9\xE5\x87\xBAU\xE7\x9B\x98\xEF\xBC\x8C\xE7\x84\xB6\xE5\x90\x8E\xE5\x88\xB7\xE6\x96\xB0\xE3\x80\x82</div>';document.getElementById('content').innerHTML=h;return}\n"
    "document.getElementById('info').textContent=d.entries.length+'\xE4\xB8\xAA\xE9\xA1\xB9\xE7\x9B\xAE | '+(d.entries.filter(function(e){return e.type==='dir'}).length)+'\xE4\xB8\xAA\xE7\x9B\xAE\xE5\xBD\x95';\n"
    "var b=document.getElementById('bread'),ps=d.path.replace(/\\/+$/,'').split('/').filter(Boolean),h='<a onclick=\"ld(\\'/SD\\')\">/SD</a>',a='/SD';\n"
    "for(var i=1;i<ps.length;i++){a+='/'+ps[i];h+=' / <a onclick=\"ld(\\''+a+'\\')\">'+esc(ps[i])+'</a>'};b.innerHTML=h;\n"
    "var c=document.getElementById('content');\n"
    "if(d.entries.length===0){c.innerHTML='<div class=\"empty\">(\xE7\xA9\xBA\xE7\x9B\xAE\xE5\xBD\x95)</div>';return}\n"
    "var frag=document.createDocumentFragment();\n"
    "d.entries.forEach(function(e){\n"
    "var div=document.createElement('div');div.className='row';\n"
    "var isImg=imgExts[e.name.split('.').pop().toLowerCase()];\n"
    "var icon=isImg?'\xF0\x9F\x96\xBC':(e.type==='dir'?'\xF0\x9F\x93\x81':'\xF0\x9F\x93\x84');\n"
    "div.innerHTML='<span class=\"icon\">'+icon+'</span><span class=\"name\">'+esc(e.name)+'</span><span class=\"size\">'+(e.type==='dir'?'':fsz(e.size))+'</span>';\n"
    "div.onclick=function(){\n"
    "if(e.type==='dir'){ld(d.path+'/'+e.name)}\n"
    "else if(isImg){cf=d.path+'/'+e.name;document.getElementById('modalImg').src='/api/file?path='+encodeURIComponent(cf)+'&action=download';document.getElementById('modal').classList.remove('hidden')}\n"
    "else{dl(d.path+'/'+e.name)}\n"
    "};\n"
    "frag.appendChild(div);\n"
    "});\n"
    "c.appendChild(frag);\n"
    "}\n"
    "function clsM(){document.getElementById('modal').classList.add('hidden');document.getElementById('modalImg').src='';cf=''}\n"
    "function dl(path){var f=document.createElement('iframe');f.style.display='none';f.src='/api/file?path='+encodeURIComponent(path)+'&action=download';document.body.appendChild(f);setTimeout(function(){document.body.removeChild(f)},10000)}\n"
    "function fsz(b){if(b<1024)return b+'B';if(b<1048576)return (b/1024).toFixed(1)+'K';return (b/1048576).toFixed(1)+'M'}\n"
    "function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML}\n"
    "ld('/SD');\n"
    "</script>\n"
    "</body>\n"
    "</html>";

#endif /* __WEB_PAGE_H_ */
